version: '3.1'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: djangoApp
      MYSQL_USER: app
      MYSQL_PASSWORD: app
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions